services:
  database:
    image: official_sql_img
    environment:
    - MYSQL_USER=abdul
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=sakila
    restart: always
    volumes:
      - my_db_data:/var/lib/mysql 

  flask-api:
    image: flask_img 
    environment:
      DATABASE_URI: "mysql://abdul:root@database:3306/sakila"
      FLASK_ENV: PRODUCTION

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8000:80"
    depends_on:
      flask-api:
        condition: service_started
      database:
        condition: service_started
      
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro

      
volumes:
  my_db_data:
